default:
   image: docker:stable

pages:
    before_script:
       - apk add --update curl wget && rm -rf /var/cache/apk/*
    stage: deploy
    script:
       - wget -c $(curl -s https://api.github.com/repos/plentico/plenti/releases/latest | grep -o 'http.*linux_64-bit.tar.gz')
       - tar -zxvf *_linux_64-bit.tar.gz
       - ./plenti build
       - npm install netlify-cli -g
       - netlify deploy --prod --dir deploy/public --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --timeout=600 --message "Deployed on $(date)"
    artifacts:
      paths:
        - public
    only:
       - main